name: cpp-linter

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - master
      - development
      - 'feature/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CPP_LINTER_GITHUB_TOKEN }}

      - name: List files
        run: ls -la
  cpp-linter:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Run C++ Linter
        uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.CPP_LINTER_GITHUB_TOKEN }}
        with:
          version: 18
          style: file
          tidy-checks: ''
          files-changed-only: false
          thread-comments: false
          step-summary: true
          file-annotations: true
          tidy-review: true
          format-review: true
          
      - name: Fail if code does not conform coding guidelines
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
