name: cpp-linter

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - master
      - development
      - 'feature/**'

jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.CPP_LINTER_GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user

  cpp-linter:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.CPP_LINTER_GITHUB_TOKEN }}
        with:
          version: 18
          style: file
          tidy-checks: ''
          files-changed-only: false
          thread-comments: false
          step-summary: true
          file-annotations: true
          tidy-review: true
          format-review: true
          
      - name: Fail if code does not conform coding guidelines
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
